name: Node CI

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: echo install
        env:
          CI: true

      - name: Run linter
        run: echo lint

      - name: Build
        run: echo build

      - name: Deploy on Zeit staging
        if: github.event_name == 'pull_request'
        uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.VERCEL_TOKEN }}
          now-org-id: ${{ secrets.ORG_ID }}
          now-project-id: ${{ secrets.PROJECT_ID }}

      - name: Deploy on Zeit production
        if: github.event_name == 'push'
        uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.VERCEL_TOKEN }}
          now-org-id: ${{ secrets.ORG_ID }}
          now-project-id: ${{ secrets.PROJECT_ID }}
          now-args: "--prod "
